import { useRouter } from "next/router";
import React, { useContext, useEffect, useRef, useState } from "react";
import { toast } from "react-hot-toast";
import axios from "axios";

import AuthButton from "@/components/auth/AuthButton";
import AuthForm from "@/components/auth/AuthForm";
import { AuthContext } from "@/provider/AuthContext";
import Head from "next/head";

const image =
  "https://res.cloudinary.com/dymjjmeyc/image/upload/v1679913069/AccountTrader/0x0_zfidbn.jpg";

const resetToken = () => {
  const { user, setLoading } = useContext(AuthContext);

  const { push, query } = useRouter();

  const [formData, setFormData] = useState({
    password: "",
    verify: "",
  });

  const change = async () => {
    setLoading(true);

    if ((formData.password.length || formData.verify.length) === 0)
      return toast.error("Талбарыг зөв гүйцэт бөглө.");

    if (formData.password !== formData.verify)
      return toast.error("Нууц үгүүдийг адилхан бичнэ үү.");

    try {
      const updated = await axios.post(
        "http://localhost:8000/api/v1/user/auth/updatePassword",
        { resetToken: query.resetToken, password: formData.password }
      );

      if (!updated.data.success)
        return toast.error("Нууц үг солих хугацаа дууссан байна.");

      toast.success("Амжилттай нууц үгээ солилоо.");

      window.close();
    } catch (error) {
      console.log(error);
    }
  };

  const passwordRef = useRef();
  const verifyRef = useRef();

  const handleKeyDown = (event) => {
    if (event.key === "Enter") {
      if (formData.password.length === 0) return passwordRef.current.focus();
      if (formData.verify.length === 0) return verifyRef.current.focus();
      change();
    }
  };

  const handlePassValue = (event) => {
    setFormData({ ...formData, password: event.target.value });
  };

  const handleVerifyValue = (event) => {
    setFormData({ ...formData, verify: event.target.value });
  };

  useEffect(() => {
    if (user !== null) push("/");
  }, [user]);

  return (
    <div className="relative w-full h-screen">
      <Head>
        <title>Change Password - SwapZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        src={image}
        className="object-cover object-center w-full h-full"
        alt=""
      />
      <div className="absolute top-0 left-0 w-full h-full flex justify-center items-center bg-black/30 px-3 xsm:px-6 sm:px-0">
        <div className="bg-white rounded-[15px] w-full sm:w-[420px] px-5 pt-8">
          <p className="w-full text-center text-[24px] font-semibold">
            Нууц үг солих
          </p>
          <div className="pt-[30px] pb-10 flex flex-col gap-5">
            <AuthForm
              type={"password"}
              inputRef={passwordRef}
              title={"Нууц үг:"}
              handleValue={handlePassValue}
              keyDownFunc={handleKeyDown}
              value={formData.password}
              placeholder={"Нууц үг ээ бичнэ үү"}
            />
            <AuthForm
              type={"password"}
              inputRef={verifyRef}
              handleValue={handleVerifyValue}
              keyDownFunc={handleKeyDown}
              value={formData.verify}
              placeholder={"Нууц үг ээ давтан бичнэ үү"}
            />
            <AuthButton title={"Солих"} onClickFunc={change} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default resetToken;
