import axios from "axios";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useContext } from "react";
import Head from "next/head";
import { toast } from "react-hot-toast";

import { AuthContext } from "@/provider/AuthContext";
import AuthBgCover from "@/components/auth/AuthBgCover";
import AuthTitle from "@/components/auth/AuthTitle";
import ForgetBody from "@/components/auth/ForgetBody";

const Forget = () => {
  const { user, setLoading } = useContext(AuthContext);

  const { push } = useRouter();

  const [email, setEmail] = useState("");

  const sendEmail = async () => {
    setLoading(true);

    try {
      const sent = await axios.post(
        "http://localhost:8000/api/v1/user/forgotPassword",
        { email }
      );

      if (!sent.data.success) return toast.error(sent.data.error.message);

      toast.success("Таны и-мэйл хаяг руу линк илгээлээ");

      push("/auth/signin");
    } catch (error) {
      console.log(error);
    }

    setLoading(false);
  };

  useEffect(() => {
    if (user !== null) push("/");
  }, [user]);

  return (
    <div className="relative w-full h-screen">
      <Head>
        <title>Forget Password - SwapZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthBgCover />
      <div className="absolute top-0 left-0 w-full h-full flex justify-center items-center bg-black/30 px-3 xsm:px-6 sm:px-0">
        <div className="bg-white rounded-[15px] w-full sm:w-[420px] px-5 pt-8">
          <AuthTitle>Нууц үг солих</AuthTitle>
          <ForgetBody sendEmail={sendEmail} email={email} setEmail={setEmail} />
        </div>
      </div>
    </div>
  );
};

export default Forget;
