import axios from "axios";
import { useRouter } from "next/router";
import Link from "next/link";
import React, { useEffect, useRef, useState } from "react";
import { useContext } from "react";

import { toast } from "react-hot-toast";
import { AuthContext } from "@/provider/AuthContext";
import AuthButton from "@/components/auth/AuthButton";
import AuthForm from "@/components/auth/AuthForm";
import Head from "next/head";

const image =
  "https://res.cloudinary.com/dymjjmeyc/image/upload/v1679913069/AccountTrader/0x0_zfidbn.jpg";

const forget = () => {
  const { user, setLoading } = useContext(AuthContext);

  const { push } = useRouter();

  const emailRef = useRef();

  const [email, setEmail] = useState("");

  const sendEmail = async () => {
    setLoading(true);

    try {
      const sent = await axios.post(
        "http://localhost:8000/api/v1/user/auth/forgotPassword",
        { email }
      );

      if (!sent.data.success) return toast.error(sent.data.error.message);

      toast.success("Таны и-мэйл хаяг руу линк илгээлээ");

      push("/auth/signin");
    } catch (error) {
      console.log(error);
    }

    setLoading(false);
  };

  const handleKeyDown = (event) => {
    if (event.key === "Enter") {
      if (email.length === 0) return emailRef.current.focus();
      sendEmail();
    }
  };

  const handleEmailValue = (event) => {
    setEmail(event.target.value);
  };

  useEffect(() => {
    if (user !== null) push("/");
  }, [user]);

  return (
    <div className="relative w-full h-screen">
      <Head>
        <title>Forget Password - SwapZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img
        src={image}
        className="object-cover object-center w-full h-full"
        alt=""
      />
      <div className="absolute top-0 left-0 w-full h-full flex justify-center items-center bg-black/30 px-3 xsm:px-6 sm:px-0">
        <div className="bg-white rounded-[15px] w-full sm:w-[420px] px-5 pt-8">
          <p className="w-full text-center text-[24px] font-semibold">
            Нууц үг солих
          </p>
          <div className="pt-[30px] pb-10 flex flex-col gap-5">
            <AuthForm
              type={"email"}
              inputRef={emailRef}
              title={"Сэргээх и-мэйл:"}
              handleValue={handleEmailValue}
              keyDownFunc={handleKeyDown}
              value={email}
              placeholder={"Сэргээх и-мэйл ээ бичнэ үү"}
            />
            <div className="w-full flex items-center justify-between">
              <Link href={"/auth/signin"}>
                <p className="cursor-pointer bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500 border-b-[1.5px] border-gradient">
                  Нэвтрэх
                </p>
              </Link>
              <Link href={"/auth/signup"}>
                <p className="cursor-pointer bg-clip-text text-transparent bg-gradient-to-t from-pink-500 to-violet-500 border-b-[1.5px] border-gradient">
                  Бүртгүүлэх
                </p>
              </Link>
            </div>
            <AuthButton title={"Сэргээх"} onClickFunc={sendEmail} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default forget;
