import axios from "axios";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import { toast } from "react-hot-toast";
import Head from "next/head";

import { AuthContext } from "@/provider/AuthContext";
import SignInButtons from "@/components/auth/SignInButtons";
import AuthTitle from "@/components/auth/AuthTitle";
import AuthBgCover from "@/components/auth/AuthBgCover";
import SignInBody from "@/components/auth/SignInBody";

export const SignIn = () => {
  const { push } = useRouter();

  const { user, setUser, setLoading } = useContext(AuthContext);

  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const login = async () => {
    setLoading(true);

    try {
      const response = await axios.post(`${process.env.BASE_URL}/user/login`, {
        email: formData.email,
        password: formData.password,
      });

      if (response.data.success !== true)
        return toast.error("Талбарыг зөв гүйцэт бөглө.");

      setUser(response.data.data.user);
      Cookies.set("token", response.data.data.token);

      if (response.data.data.user.role === "admin") {
        push("/admin");
        return;
      }

      toast.success("Амжилттай нэвтэрлээ.");

      push("/");
    } catch (error) {
      console.log(error);
    }

    setLoading(false);
  };

  useEffect(() => {
    if (user !== null) push("/");
  }, [user]);

  return (
    <div className="relative w-full h-screen">
      <Head>
        <title>Login - SwapZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthBgCover />
      <div className="absolute top-0 left-0 w-full h-full flex justify-center items-center bg-black/30 px-3 xsm:px-6 sm:px-0">
        <div className="bg-white rounded-[15px] w-full sm:w-[420px] px-5 py-8">
          <AuthTitle>Нэвтрэх</AuthTitle>
          <SignInBody
            formData={formData}
            setFormData={setFormData}
            login={login}
          />
          <SignInButtons />
        </div>
      </div>
    </div>
  );
};

export default SignIn;
