import Head from "next/head";

import { Footer } from "./Footer";
import { Navbar } from "./Navbar";

export const Layout = ({ children, title }) => {
  return (
    <div
      className={`relative flex flex-col justify-between min-h-screen w-full`}
    >
      <Head>
        <title>{title ? title + " - SwapZone" : "SwapZone"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="bg-[#f4f4f4] grow h-full w-full">{children}</main>
      <Footer />
    </div>
  );
};
