import Head from "next/head";
import Footer from "./Footer";
import Navbar from "./Navbar";

export default function Layout({ children, title }) {
  return (
    <div className="flex flex-col justify-between min-h-screen w-full">
      <Head>
        <title>{title ? title + "- SwapZone" : "SwapZone"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
